version: "3.9"

services:

  app:
    build: .
    container_name: pocketmarket-api

    volumes:
      - uploads_data:/app/uploads

    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}

      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_PROFILES_ACTIVE: docker

      API_SECURITY_TOKEN_SECRET: ${API_SECURITY_TOKEN_SECRET}
      POKEMON_TCG_API_KEY: ${POKEMON_TCG_API_KEY:-}

    ports:
      - "8080:8080"

    networks:
      - pocket-network

    restart: always


volumes:
  uploads_data:


networks:
  pocket-network:
    driver: bridge