spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pocketmarket
    username: postgres
    password: 3124
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

api:
  security:
    token:
      secret: pocketmarket-secret-jwt-2026